import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1762798386010 implements MigrationInterface {
    name = 'InitialSchema1762798386010'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pedido" DROP CONSTRAINT "pedido_cliente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "envio" DROP CONSTRAINT "envio_pedido_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "envio" DROP CONSTRAINT "envio_repartidor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "producto" DROP CONSTRAINT "producto_categoria_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" DROP CONSTRAINT "carrito_item_cliente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" DROP CONSTRAINT "carrito_item_producto_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "calificacion" DROP CONSTRAINT "calificacion_pedido_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "calificacion" DROP CONSTRAINT "calificacion_cliente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lote" DROP CONSTRAINT "lote_producto_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lote" DROP CONSTRAINT "lote_proveedor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" DROP CONSTRAINT "movimiento_stock_producto_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" DROP CONSTRAINT "movimiento_stock_lote_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" DROP CONSTRAINT "movimiento_stock_usuario_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "promocion" DROP CONSTRAINT "promocion_producto_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "calificacion" DROP CONSTRAINT "calificacion_puntuacion_check"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" DROP CONSTRAINT "carrito_item_cliente_id_producto_id_key"`);
        await queryRunner.query(`ALTER TABLE "usuario" RENAME COLUMN "fecha_creacion" TO "is_active"`);
        await queryRunner.query(`ALTER TABLE "producto" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "pedido" DROP COLUMN "fecha_pedido"`);
        await queryRunner.query(`ALTER TABLE "pedido" ADD "fecha_pedido" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."estado_pedido" RENAME TO "estado_pedido_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pedido_estado_enum" AS ENUM('pendiente', 'procesando', 'en camino', 'entregado', 'devuelto', 'cancelado')`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "estado" TYPE "public"."pedido_estado_enum" USING "estado"::"text"::"public"."pedido_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "estado" SET DEFAULT 'pendiente'`);
        await queryRunner.query(`DROP TYPE "public"."estado_pedido_old"`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "total_pedido" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "total_pedido" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedido" DROP COLUMN "metodo_pago"`);
        await queryRunner.query(`ALTER TABLE "pedido" ADD "metodo_pago" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "cliente_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."estado_pedido" RENAME TO "estado_pedido_old"`);
        await queryRunner.query(`CREATE TYPE "public"."envio_estado_enum" AS ENUM('pendiente', 'procesando', 'en camino', 'entregado', 'devuelto', 'cancelado')`);
        await queryRunner.query(`ALTER TABLE "envio" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "envio" ALTER COLUMN "estado" TYPE "public"."envio_estado_enum" USING "estado"::"text"::"public"."envio_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "envio" ALTER COLUMN "estado" SET DEFAULT 'pendiente'`);
        await queryRunner.query(`DROP TYPE "public"."estado_pedido_old"`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP CONSTRAINT "categoria_nombre_key"`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD CONSTRAINT "UQ_6771d90221138c5bf48044fd73d" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "producto" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "producto" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "producto" ALTER COLUMN "precio_venta" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "producto" DROP COLUMN "unidad_medida"`);
        await queryRunner.query(`ALTER TABLE "producto" ADD "unidad_medida" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "producto" ALTER COLUMN "stock_disponible" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "producto" ALTER COLUMN "categoria_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ALTER COLUMN "fecha_agregado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ALTER COLUMN "fecha_agregado" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "calificacion" ALTER COLUMN "fecha_calificacion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "calificacion" ALTER COLUMN "fecha_calificacion" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "nombre_empresa"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "nombre_empresa" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "contacto_nombre"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "contacto_nombre" character varying`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "telefono" character varying`);
        await queryRunner.query(`ALTER TABLE "proveedor" ALTER COLUMN "fecha_creacion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proveedor" ALTER COLUMN "fecha_creacion" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "lote" ALTER COLUMN "fecha_recibida" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."tipo_movimiento" RENAME TO "tipo_movimiento_old"`);
        await queryRunner.query(`CREATE TYPE "public"."movimiento_stock_tipo_enum" AS ENUM('entrada_compra', 'salida_venta', 'ajuste_vencido', 'ajuste_devolucion')`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ALTER COLUMN "tipo" TYPE "public"."movimiento_stock_tipo_enum" USING "tipo"::"text"::"public"."movimiento_stock_tipo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tipo_movimiento_old"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ALTER COLUMN "fecha_movimiento" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ALTER COLUMN "fecha_movimiento" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "nombre_completo"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "nombre_completo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "usuario_email_key"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "UQ_2863682842e688ca198eb25c124" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."rol_usuario" RENAME TO "rol_usuario_old"`);
        await queryRunner.query(`CREATE TYPE "public"."usuario_rol_enum" AS ENUM('Administrador', 'Vendedor', 'Almacen', 'Repartidor', 'Cliente', 'Soporte', 'Proveedor')`);
        await queryRunner.query(`ALTER TABLE "usuario" ALTER COLUMN "rol" TYPE "public"."usuario_rol_enum" USING "rol"::"text"::"public"."usuario_rol_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rol_usuario_old"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "promocion" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "promocion" ADD "descripcion" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "promocion" DROP COLUMN "tipo_descuento"`);
        await queryRunner.query(`ALTER TABLE "promocion" ADD "tipo_descuento" character varying`);
        await queryRunner.query(`ALTER TABLE "calificacion" ADD CONSTRAINT "CHK_f83ce86d4becdabf6231376512" CHECK ("puntuacion" >= 1 AND "puntuacion" <= 5)`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ADD CONSTRAINT "UQ_ad41b86f8126d5a6f8491796f5e" UNIQUE ("cliente_id", "producto_id")`);
        await queryRunner.query(`ALTER TABLE "pedido" ADD CONSTRAINT "FK_ab19fb380d17682f87649eded89" FOREIGN KEY ("cliente_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "envio" ADD CONSTRAINT "FK_bfb5b4dfbb3d0b8c2e311af2386" FOREIGN KEY ("pedido_id") REFERENCES "pedido"("pedido_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "envio" ADD CONSTRAINT "FK_fd7994e74d74438145087e368c4" FOREIGN KEY ("repartidor_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto" ADD CONSTRAINT "FK_1ae19a0cb542cf735d454bab0b5" FOREIGN KEY ("categoria_id") REFERENCES "categoria"("categoria_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ADD CONSTRAINT "FK_595f0418b5ca3421718119b07af" FOREIGN KEY ("cliente_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ADD CONSTRAINT "FK_0949d87ae77ce0ed6416e3e1665" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion" ADD CONSTRAINT "FK_eb8647b917a525b7642dcb92c8b" FOREIGN KEY ("pedido_id") REFERENCES "pedido"("pedido_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion" ADD CONSTRAINT "FK_36132ddc82b2c29b7154f27275f" FOREIGN KEY ("cliente_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote" ADD CONSTRAINT "FK_7dadfaf63a50e59787a233f1410" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote" ADD CONSTRAINT "FK_faacd3e1691ed70659f4ba03ff1" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor"("proveedor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ADD CONSTRAINT "FK_710f568fa31814d122557802f62" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ADD CONSTRAINT "FK_bfd9b1727a890c5d43b95b2d234" FOREIGN KEY ("lote_id") REFERENCES "lote"("lote_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ADD CONSTRAINT "FK_7bcb47a863c1926656d60d2e0a4" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promocion" ADD CONSTRAINT "FK_a8631378d07664795a104b87e93" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "promocion" DROP CONSTRAINT "FK_a8631378d07664795a104b87e93"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" DROP CONSTRAINT "FK_7bcb47a863c1926656d60d2e0a4"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" DROP CONSTRAINT "FK_bfd9b1727a890c5d43b95b2d234"`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" DROP CONSTRAINT "FK_710f568fa31814d122557802f62"`);
        await queryRunner.query(`ALTER TABLE "lote" DROP CONSTRAINT "FK_faacd3e1691ed70659f4ba03ff1"`);
        await queryRunner.query(`ALTER TABLE "lote" DROP CONSTRAINT "FK_7dadfaf63a50e59787a233f1410"`);
        await queryRunner.query(`ALTER TABLE "calificacion" DROP CONSTRAINT "FK_36132ddc82b2c29b7154f27275f"`);
        await queryRunner.query(`ALTER TABLE "calificacion" DROP CONSTRAINT "FK_eb8647b917a525b7642dcb92c8b"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" DROP CONSTRAINT "FK_0949d87ae77ce0ed6416e3e1665"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" DROP CONSTRAINT "FK_595f0418b5ca3421718119b07af"`);
        await queryRunner.query(`ALTER TABLE "producto" DROP CONSTRAINT "FK_1ae19a0cb542cf735d454bab0b5"`);
        await queryRunner.query(`ALTER TABLE "envio" DROP CONSTRAINT "FK_fd7994e74d74438145087e368c4"`);
        await queryRunner.query(`ALTER TABLE "envio" DROP CONSTRAINT "FK_bfb5b4dfbb3d0b8c2e311af2386"`);
        await queryRunner.query(`ALTER TABLE "pedido" DROP CONSTRAINT "FK_ab19fb380d17682f87649eded89"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" DROP CONSTRAINT "UQ_ad41b86f8126d5a6f8491796f5e"`);
        await queryRunner.query(`ALTER TABLE "calificacion" DROP CONSTRAINT "CHK_f83ce86d4becdabf6231376512"`);
        await queryRunner.query(`ALTER TABLE "promocion" DROP COLUMN "tipo_descuento"`);
        await queryRunner.query(`ALTER TABLE "promocion" ADD "tipo_descuento" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "promocion" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "promocion" ADD "descripcion" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "is_active" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."rol_usuario_old" AS ENUM('Administrador', 'Vendedor', 'Almacen', 'Repartidor', 'Cliente', 'Soporte', 'Proveedor')`);
        await queryRunner.query(`ALTER TABLE "usuario" ALTER COLUMN "rol" TYPE "public"."rol_usuario_old" USING "rol"::"text"::"public"."rol_usuario_old"`);
        await queryRunner.query(`DROP TYPE "public"."usuario_rol_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."rol_usuario_old" RENAME TO "rol_usuario"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "UQ_2863682842e688ca198eb25c124"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "usuario_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "nombre_completo"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "nombre_completo" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ALTER COLUMN "fecha_movimiento" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ALTER COLUMN "fecha_movimiento" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."tipo_movimiento_old" AS ENUM('entrada_compra', 'salida_venta', 'ajuste_vencido', 'ajuste_devolucion')`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ALTER COLUMN "tipo" TYPE "public"."tipo_movimiento_old" USING "tipo"::"text"::"public"."tipo_movimiento_old"`);
        await queryRunner.query(`DROP TYPE "public"."movimiento_stock_tipo_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."tipo_movimiento_old" RENAME TO "tipo_movimiento"`);
        await queryRunner.query(`ALTER TABLE "lote" ALTER COLUMN "fecha_recibida" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "proveedor" ALTER COLUMN "fecha_creacion" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "proveedor" ALTER COLUMN "fecha_creacion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "telefono" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "contacto_nombre"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "contacto_nombre" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "proveedor" DROP COLUMN "nombre_empresa"`);
        await queryRunner.query(`ALTER TABLE "proveedor" ADD "nombre_empresa" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "calificacion" ALTER COLUMN "fecha_calificacion" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "calificacion" ALTER COLUMN "fecha_calificacion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ALTER COLUMN "fecha_agregado" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ALTER COLUMN "fecha_agregado" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "producto" ALTER COLUMN "categoria_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "producto" ALTER COLUMN "stock_disponible" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "producto" DROP COLUMN "unidad_medida"`);
        await queryRunner.query(`ALTER TABLE "producto" ADD "unidad_medida" character varying(20) NOT NULL DEFAULT 'unidad'`);
        await queryRunner.query(`ALTER TABLE "producto" ALTER COLUMN "precio_venta" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "producto" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "producto" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP CONSTRAINT "UQ_6771d90221138c5bf48044fd73d"`);
        await queryRunner.query(`ALTER TABLE "categoria" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD "nombre" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categoria" ADD CONSTRAINT "categoria_nombre_key" UNIQUE ("nombre")`);
        await queryRunner.query(`CREATE TYPE "public"."estado_pedido_old" AS ENUM('pendiente', 'procesando', 'en camino', 'entregado', 'devuelto', 'cancelado')`);
        await queryRunner.query(`ALTER TABLE "envio" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "envio" ALTER COLUMN "estado" TYPE "public"."estado_pedido_old" USING "estado"::"text"::"public"."estado_pedido_old"`);
        await queryRunner.query(`ALTER TABLE "envio" ALTER COLUMN "estado" SET DEFAULT 'pendiente'`);
        await queryRunner.query(`DROP TYPE "public"."envio_estado_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_pedido_old" RENAME TO "estado_pedido"`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "cliente_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedido" DROP COLUMN "metodo_pago"`);
        await queryRunner.query(`ALTER TABLE "pedido" ADD "metodo_pago" character varying(50) DEFAULT 'contra_entrega'`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "total_pedido" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "total_pedido" TYPE numeric(10,2)`);
        await queryRunner.query(`CREATE TYPE "public"."estado_pedido_old" AS ENUM('pendiente', 'procesando', 'en camino', 'entregado', 'devuelto', 'cancelado')`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "estado" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "estado" TYPE "public"."estado_pedido_old" USING "estado"::"text"::"public"."estado_pedido_old"`);
        await queryRunner.query(`ALTER TABLE "pedido" ALTER COLUMN "estado" SET DEFAULT 'pendiente'`);
        await queryRunner.query(`DROP TYPE "public"."pedido_estado_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."estado_pedido_old" RENAME TO "estado_pedido"`);
        await queryRunner.query(`ALTER TABLE "pedido" DROP COLUMN "fecha_pedido"`);
        await queryRunner.query(`ALTER TABLE "pedido" ADD "fecha_pedido" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "producto" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "usuario" RENAME COLUMN "is_active" TO "fecha_creacion"`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ADD CONSTRAINT "carrito_item_cliente_id_producto_id_key" UNIQUE ("cliente_id", "producto_id")`);
        await queryRunner.query(`ALTER TABLE "calificacion" ADD CONSTRAINT "calificacion_puntuacion_check" CHECK (((puntuacion >= 1) AND (puntuacion <= 5)))`);
        await queryRunner.query(`ALTER TABLE "promocion" ADD CONSTRAINT "promocion_producto_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ADD CONSTRAINT "movimiento_stock_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ADD CONSTRAINT "movimiento_stock_lote_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "lote"("lote_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_stock" ADD CONSTRAINT "movimiento_stock_producto_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote" ADD CONSTRAINT "lote_proveedor_id_fkey" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor"("proveedor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote" ADD CONSTRAINT "lote_producto_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion" ADD CONSTRAINT "calificacion_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion" ADD CONSTRAINT "calificacion_pedido_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "pedido"("pedido_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ADD CONSTRAINT "carrito_item_producto_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "producto"("producto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrito_item" ADD CONSTRAINT "carrito_item_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto" ADD CONSTRAINT "producto_categoria_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "categoria"("categoria_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "envio" ADD CONSTRAINT "envio_repartidor_id_fkey" FOREIGN KEY ("repartidor_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "envio" ADD CONSTRAINT "envio_pedido_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "pedido"("pedido_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedido" ADD CONSTRAINT "pedido_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "usuario"("usuario_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
